
# -*- coding: utf-8 -*-
"""AirQualityProject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwGFLJfhZ81snp8vF9wOOtE-3oafAFpE
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("Connecting to Google Drive...")
drive.mount('/content/drive')


project_folder = '/content/drive/MyDrive/AirQualityProject/'
csv_path = os.path.join(project_folder, 'air_pollution_data.csv')

if not os.path.exists(csv_path):
    raise FileNotFoundError(f"Could not find 'air_pollution_data.csv' at {csv_path}. Please verify your folder name.")

print("Successfully linked! Loading dataset...")

df = pd.read_csv(csv_path)

# Parse dates and sort chronologically
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')
df = df.sort_values(by=['city', 'date']).reset_index(drop=True)

# Isolating a single city to track strict local timeline trends (e.g., Ahmedabad)
city_df = df[df['city'] == 'Ahmedabad'].copy()

# Handle missing data points using linear interpolation
pollutant_cols = ['co', 'no', 'no2', 'o3', 'so2', 'pm2_5', 'pm10', 'nh3']
for col in pollutant_cols:
    city_df[col] = city_df[col].interpolate(method='linear')

target_variable = 'pm2_5'

# Create lookback features (Lags)
city_df['target_lag_1'] = city_df[target_variable].shift(1)
city_df['target_lag_2'] = city_df[target_variable].shift(2)
city_df['target_lag_7'] = city_df[target_variable].shift(7)

# Create rolling timeline windows
city_df['target_roll_mean_3'] = city_df[target_variable].shift(1).rolling(window=3).mean()
city_df['target_roll_mean_7'] = city_df[target_variable].shift(1).rolling(window=7).mean()

# Encode calendar components cyclically using Sine and Cosine
city_df['month'] = city_df['date'].dt.month
city_df['month_sin'] = np.sin(2 * np.pi * city_df['month'] / 12.0)
city_df['month_cos'] = np.cos(2 * np.pi * city_df['month'] / 12.0)

# Drop rows where shifting/lags created NaN values
city_df = city_df.dropna().reset_index(drop=True)

features = [
    'co', 'no', 'no2', 'o3', 'so2', 'pm10', 'nh3',
    'target_lag_1', 'target_lag_2', 'target_lag_7',
    'target_roll_mean_3', 'target_roll_mean_7',
    'month_sin', 'month_cos'
]

# Splitting using a hard date to keep future testing data pristine
split_date = pd.to_datetime('2022-12-31')
train_mask = city_df['date'] <= split_date
test_mask = city_df['date'] > split_date

X_train, y_train = city_df.loc[train_mask, features], city_df.loc[train_mask, target_variable]
X_test, y_test = city_df.loc[test_mask, features], city_df.loc[test_mask, target_variable]
test_dates = city_df.loc[test_mask, 'date']

print(f"Data split successfully! Training shapes: {X_train.shape}, Testing shapes: {X_test.shape}")

print("Training Random Forest Regressor...")
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

# Predict target values on unseen test data
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("\n" + "="*40)
print("     MODEL EVALUATION METRICS REPORT     ")
print("="*40)
print(f"Mean Absolute Error (MAE)      : {mae:.2f}")
print(f"Root Mean Square Error (RMSE)  : {rmse:.2f}")
print(f"R-squared Score (R²)           : {r2:.2f}")
print("="*40 + "\n")

# Plot 1: Actual vs Predicted Performance Line Graph
plt.figure(figsize=(14, 6))
sns.lineplot(x=test_dates, y=y_test, label='Actual PM2.5 Levels', color='teal', alpha=0.8)
sns.lineplot(x=test_dates, y=y_pred, label='Predicted PM2.5 Levels', color='coral', linestyle='--')
plt.title('Air Quality Regression Analysis: Actual vs Predicted PM2.5 Levels (Test Set)')
plt.xlabel('Date Timeline')
plt.ylabel('Concentration Levels')
plt.legend()
plt.grid(True, linestyle=':', alpha=0.6)
plt.tight_layout()
plt.show()

# Plot 2: Feature Importance Breakdown
importance = model.feature_importances_
feat_imp = pd.Series(importance, index=features).sort_values(ascending=False)

plt.figure(figsize=(10, 5))
sns.barplot(x=feat_imp.values, y=feat_imp.index, palette='viridis')
plt.title('Feature Contribution Breakdown to Model Predictions')
plt.xlabel('Relative Gini Importance Score')
plt.ylabel('Feature Columns')
plt.tight_layout()
plt.show()